### ISSUE TITLE
[Bug]: cd-dev 동작 이후 404 에러 발생

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#1026]
### Describe the bug

main 브랜치에 PR이 merge되면 [cd-dev workflow](https://github.com/skkuding/codedang/blob/main/.github/workflows/cd-dev.yml)가 동작하면서 스테이지 서버에 배포됩니다. ([dev.codedang.com](https://dev.codedang.com))

이 때 배포 후 Caddy에서 404 에러가 발생합니다.

배포 후 Caddy 컨테이너를 보면 HTML, CSS, JS가 담긴 /var/www/html 폴더가 비어있는데, Docker mount된 파일을 변경하였을 때 Caddy 컨테이너에 반영이 안되는 문제로 추정됩니다.
관련 글: [Docker mounted file is not updating? Your text editor probably updated the file inode.](https://medium.com/@jonsbun/why-need-to-be-careful-when-mounting-single-files-into-a-docker-container-4f929340834)

![image](https://github.com/skkuding/codedang/assets/19747913/20a5c597-44b4-4ca2-8769-de078479ec44)

### Reproduction

1. trigger cd-dev

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
@Kang-Eunsu 이거 해결 된 건가요?

**Comment by k1g99** [comment]
> @Kang-Eunsu 이거 해결 된 건가요?

아뇨.... 이거 지금 은수가 fork 해서 테스트 중인데,,,, 왜 close된거지?

**Comment by ssupecial** [comment]
아 제가 커밋을 제 개인 레포에서 PR을 했어야하는데 codedang으로 잘못 해서 저렇게 된 것 같습니다. 죄송합니다.
1번 서버에서 테스트 완료했고, 해결이 되어서 금일 프론트 미팅 끝난 이후에 원본 레포로 적용해보겠습니다.

**Comment by dotoleeoak** [comment]
> 아 제가 커밋을 제 개인 레포에서 PR을 했어야하는데 codedang으로 잘못 해서 저렇게 된 것 같습니다. 죄송합니다. 1번 서버에서 테스트 완료했고, 해결이 되어서 금일 프론트 미팅 끝난 이후에 원본 레포로 적용해보겠습니다.

넹~
