### ISSUE TITLE
NextJs 회원가입 모달

### ISSUE THREAD

**Issue by EliseCho13** [skkuding/codedang#1036]
### Describe the problem and solution

NextJs에서 회원가입 모달을 만듭니다.
React Hook Form과 Zod를 사용합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by EliseCho13** [comment]
Vue에서 Username을 입력받던 것과 달리, NextJs의 로그인 모달에서 User Id를 입력받고 있습니다
회원가입도 마찬가지로 User Id를 입력하도록 해야 하나요?

**Comment by dotoleeoak** [comment]
@EliseCho13 넹 일단 'User ID'로 이름만 수정해주세요 (API에는 똑같이 'username'으로 하면 됩니다)
