### ISSUE TITLE
NextJs 토스트 만들기

### ISSUE THREAD

**Issue by EliseCho13** [skkuding/codedang#1037]
### Describe the problem and solution

'info', 'success', 'warn', 'error'의 타입에 따라 달라지는 토스트를 만든다
frontend/src/common/components/Atom/Toast.vue 및 frontend/src/common/composables/toast.ts 참조
이슈 #1036 에 필요

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
@EliseCho13 shadcn에 있는 toast는 어떤가염
https://ui.shadcn.com/docs/components/toast

**Comment by EliseCho13** [comment]
오호 좋은데요? 요거 쓰겠습니다!
이슈 닫을까요?

**Comment by dotoleeoak** [comment]
예엡
