### ISSUE TITLE
Main Page 만들기

### ISSUE THREAD

**Issue by youznn** [skkuding/codedang#1043]
### Describe the problem and solution

main page
- 캐러셀 추가하기
- card 추가하기
- footer 추가하기

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
deprecated issue
