### ISSUE TITLE
Problem Editor Page

### ISSUE THREAD

**Issue by jihorobert** [skkuding/codedang#1131]
### Describe the problem and solution

- layout 짜기
- Monaco 혹은 CodeMirror 에디터 사용 예정

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
구현되어 있음
