### ISSUE TITLE
Contest 목록 페이지 구현

### ISSUE THREAD

**Issue by B0XERCAT** [skkuding/codedang#1136]
### Describe the problem and solution

Cover, Card, Data Table로
Contest 목록 페이지를 만들어 봅시다

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
구현되어 있음
