### ISSUE TITLE
Problem 목록 정렬 기능

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#1141]
### Describe the problem and solution

Problem 목록을 정렬하여 보여주는 옵션을 추가합니다.
(정렬 기준: ID, Level, Submission, Solved Rate)

<img width="257" alt="image" src="https://github.com/skkuding/codedang/assets/19747913/bb25e360-54dd-4357-ae2d-bf1ec7d267c6">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by SH9480P** [comment]
#1123 중복인 것 같아요~
