### ISSUE TITLE
[Bug]: Iris cache invalidation

### ISSUE THREAD

**Issue by JungangHighschool** [skkuding/codedang#1176]
### Describe the bug

테스트 케이스가 수정될 시, iris의 cache에는 이전 버전의 테스트 케이스가 저장되어 있어 잘못된 채점이 이루어질 가능성이 있습니다.

### Reproduction

1. 백앤드에서 테스트 케이스를 수정할 때, iris로 cache invalidation 메세지를 보내줍니다.

하기 구성도를 참고합니다.
![image](https://github.com/skkuding/codedang/assets/48322716/e9e9de1c-c365-4b19-99c9-fc30912e8c1c)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by gyunseo** [comment]
iris로 cache invalidation 메세지를 보내준 이후, 이전의 테스트 케이스로 채점된 submission들을 재채점하는 issue를 분리합니다.
