### ISSUE TITLE
Contest 참여자 순위, 문제별 획득 점수 조회 기능 추가

### ISSUE THREAD

**Issue by SH9480P** [skkuding/codedang#1203]
### Describe the problem and solution

단일 contest 조회 시, 해당 contest에 참여한 사람들의 **등수**와 **문제별 획득 점수**, **총 점수**, **푼 문제 수**를 같이 조회할 수 있어야 합니다.
현재는 몇 명이 참여했는지만 알 수 있습니다.

총 점수와 푼 문제 수를 ContestRecord에 추가하고, 이를 활용하여 정렬한 뒤 반환함으로써 등수를 제공할 수 있을 듯 합니다.
이와 같은 방법을 취하려면 submission이 이루어질 때마다 푼 문제 수와 총 점수를 ContestRecord에 업데이트하는 로직 또한 추가할 필요가 있습니다.

일부 테스트케이스만 통과하지 못했을 때, 해당 문제의 점수를 0점으로 할지, 문제의 배점을 통과한 테스트케이스 수로 나눈 값을 점수로 할지 의사결정이 필요합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by gyunseo** [comment]
contest에서 user가 problem AC를 받은 개수에 따른 점수와 user가 problem을 풀었을 때 통과한 testcase에 따른 점수 구분이 필요해 보입니다.
