### ISSUE TITLE
query based api 적용

### ISSUE THREAD

**Issue by jihorobert** [skkuding/codedang#1222]
### Describe the problem and solution

- 기존 param-based 경로를 query-based로 변경

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
해결된 거 같아서 닫아둘게용
