### ISSUE TITLE
[Bug]: GraphQL API 호출 시 CursorValidationPipe 에러 발생

### ISSUE THREAD

**Issue by SH9480P** [skkuding/codedang#1234]
### Describe the bug

GQL 서버에 쿼리를 보낼 때, cursor 필드가 포함되면 유효한 값임에도 에러가 납니다. (하단 참고)

### Reproduction

1. 개발 서버에 쿼리 보내기
```gql
query {
  getContests(
    groupId: 1
    cursor: 1
    take: 10
  ) {
    id
    title
    description
    startTime
    endTime
  }
}
```

### Logs
```json
{
  "errors": [
    {
      "message": "Cursor must be a positive number",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "getContests"
      ],
      "extensions": {
        "code": "BAD_REQUEST",
        "originalError": {
          "message": "Cursor must be a positive number",
          "error": "Bad Request",
          "statusCode": 400
        }
      }
    }
  ],
  "data": null
}
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by Jaehyeon1020** [comment]
https://github.com/skkuding/codedang/pull/1235 이거 해결하다보니 에러가 없어졌는데 .. 확인 부탁드립니다 😭

**Comment by SH9480P** [comment]
> #1235 이거 해결하다보니 에러가 없어졌는데 .. 확인 부탁드립니다 😭

고생하셨습니다! float을 허용하도록 구현된 점이 살짝 아쉬운 부분이긴 하네요..
