### ISSUE TITLE
Contest page table 케이스 분리 및 status 추가

### ISSUE THREAD

**Issue by youznn** [skkuding/codedang#1236]
### Describe the problem and solution

contest page list의 테이블을 registered와 finished로 분리합니다.
status를 추가합니다. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
기획 변경으로 구현하지 않음
