### ISSUE TITLE
Tailwind CSS color set 추가

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#139]
### Describe the problem and solution

https://github.com/skkuding/next/pull/123#issuecomment-1186811083 에서 언급한대로 색상 종류를 늘립니다.
직접 hex 값으로 색상을 바꾸면 자유도는 높아지지만 전반적인 일관성이나 어울림이 깨지기 때문에 미리 정의된 color set을 사용하는 것이 좋습니다.

참고) "디자인 시스템이 필요한 이유" https://simsimjae.medium.com/%EB%94%94%EC%9E%90%EC%9D%B8-%EC%8B%9C%EC%8A%A4%ED%85%9C%EC%9D%98-%EC%A0%95%EC%9D%98%EC%99%80-%ED%95%84%EC%9A%94%EC%84%B1-2d76d424ac03

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by SOLBI1028** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/75013515/181400035-20c5b991-5772-4778-ab69-70bdad8d66f9.png">

색상을 레벨 색깔(무지개)과 무지개색깔에서 더 다양한 선택지를 주는 방색으로 결정해보았는데 어떤가요?!

**Comment by dotoleeoak** [comment]
> 색상을 레벨 색깔(무지개)과 무지개색깔에서 더 다양한 선택지를 주는 방색으로 결정해보았는데 어떤가요?!

@SOLBI1028 넵 좋습니다!
저는 회색 계열도 tailwind 기본 색상을 조금 더 사용했으면 좋겠는데 어떨까요?
지금은 config에 slate만 있던데 아예 프로젝트에 사용하는 회색 계열을 slate로 통일하거나 다른 회색을 추가하는 게 좋아보여요

![image](https://user-images.githubusercontent.com/19747913/183533503-76a3583d-ffbb-4712-bcaf-45eef2149047.png)
