### ISSUE TITLE
[Bug]: Contest 또는 Workbook에 대한 Submission을 생성할 때 contestId, workbookId가 저장되지 않는 문제

### ISSUE THREAD

**Issue by Jaehyeon1020** [skkuding/codedang#1534]
### Describe the bug

createSubmission 함수에서 Contest 또는 Workbook에 대한 Submission을 생성할 때 contestId, workbookId가 저장되지 않는 문제가 있습니다.

### Reproduction

1. contestId 또는 workbookId가 들어오는 경우 submission data에 포함되도록 수정
2.
3.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by aintbe** [comment]
이거 혹시 작업 중이신가요? 다른 브랜치에서 작업하고 있는데 아직 PR을 올리지 않아서요!!😅

**Comment by Jaehyeon1020** [comment]
> 이거 혹시 작업 중이신가요? 다른 브랜치에서 작업하고 있는데 아직 PR을 올리지 않아서요!!😅

헐 작업중인데 혹시 작업 하고계셨었나요 ...!
