### ISSUE TITLE
Problem DB 필드 중 isVisible 및 exposeTime 통합

### ISSUE THREAD

**Issue by cho-to** [skkuding/codedang#1644]
### Describe the bug

problem 필드에서 원래는 isVisible, exposeTime 필드 둘 다 있어 problem의 exposeTime이 지나도 isVisible 상태가 False 면 화면에서 보이지 않았습니다.
두개 필드가 의미적으로 충돌하는 것 같아 exposeTime 필드 하나로 통합하려 합니다.

### Reproduction

.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-616 Problem DB 필드 중 isVisible 및 exposeTime 통합](https://www.notion.so/Problem-DB-isVisible-exposeTime-cf3ed0a0e087498db11b483786abc3c3)
