### ISSUE TITLE
CommandList 관련 cmdk breaking change 문제

### ISSUE THREAD

**Issue by jihorobert** [skkuding/codedang#1662]
### Describe the problem and solution

CommandList 관련 cmdk breaking change 문제

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
해결 완료
