### ISSUE TITLE
무한스크롤 컴포넌트 하나로 통일

### ISSUE THREAD

**Issue by youznn** [skkuding/codedang#1689]
### Describe the problem and solution

현재 무한스크롤을 이용하는 테이블이 여러개인데 하나의 컴포넌트로 묶어서 유지보수를 용이하게 합니다

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-614 무한스크롤 컴포넌트 하나로 통일](https://www.notion.so/2c48a48fa9fe4fc788a2b663e8f1e1a5)
