### ISSUE TITLE
Admin 문제 생성시 스켈레톤 코드 저장

### ISSUE THREAD

**Issue by jihorobert** [skkuding/codedang#1749]
### Describe the problem and solution

- Admin 문제 생성시 스켈레톤 코드 저장

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-622 Admin 문제 생성시 스켈레톤 코드 저장](https://www.notion.so/Admin-f8692aba9f354f618fa402b57e3dd058)
