### ISSUE TITLE
Fix Notice Stage Server Error

### ISSUE THREAD

**Issue by jihorobert** [skkuding/codedang#1764]
### Describe the problem and solution

Stage 서버에서 Notice 페이지에 들어갔을때 발생 에러 해결

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
해결 완료
