### ISSUE TITLE
[Bug]: Submission 조회할 때 user의 ID가 null인 경우 런타임 에러 발생

### ISSUE THREAD

**Issue by jwoojin9** [skkuding/codedang#1768]
### Describe the bug

문제의 submission 목록을 조회할 때 user의 ID가 null인 경우 런타임 에러가 발생

### Reproduction

1. /problem/1/submission에서 4번째 목록 클릭

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-620 [Bug]: Submission 조회할 때 user의 ID가 null인 경우 런타임 에러 발생](https://www.notion.so/Bug-Submission-user-ID-null-680780cd8f154467a67c8b72d70770c0)
