### ISSUE TITLE
ResolveField 중복 호출 수정

### ISSUE THREAD

**Issue by cho-to** [skkuding/codedang#1770]
### Describe the problem and solution

admin 서버 내의 `problem.service.ts` 및 `problem.resolver.ts` 중 ResolveField 및 prisma include로 인한 DB 중복호출 건을 수정합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-623 ResolveField 중복 호출 수정](https://www.notion.so/ResolveField-683f3403d1ca4e62829a7358d481f5c8)
