### ISSUE TITLE
특정 User의 특정 Contest에 대한 제출내역/성적 조회

### ISSUE THREAD

**Issue by Jaehyeon1020** [skkuding/codedang#1884]
### Describe the problem and solution

특정 User의 특정 Contest에 대한 제출내역/성적 조회 API를 작성합니다.

### Notion task

TAS-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Notion task와 Github issue 연동 ](https://www.notion.so/Notion-task-Github-issue-8863eff3832440179f5abd68038c138f)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Notion task와 Github issue 연동 ](https://www.notion.so/Notion-task-Github-issue-8863eff3832440179f5abd68038c138f)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Notion task와 Github issue 연동 ](https://www.notion.so/Notion-task-Github-issue-8863eff3832440179f5abd68038c138f)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [특정 User의 특정 Contest에 대한 제출내역/성적 조회](https://www.notion.so/User-Contest-8d9497c4136d46f18799bf0257a006ff)
