### ISSUE TITLE
Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기

### ISSUE THREAD

**Issue by hwantae** [skkuding/codedang#1885]
### Describe the problem and solution

contest id를 받고 그 id에 해당되는 성적들과 유저정보들을 가져온다

### Notion task

TAS-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Notion task와 Github issue 연동 ](https://www.notion.so/Notion-task-Github-issue-8863eff3832440179f5abd68038c138f)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기](https://www.notion.so/Participant-page-contest-ffcecb73118249d686cdc3f9395472ae)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기](https://www.notion.so/Participant-page-contest-d401b57781df4d3cb65eb89676e20e6b)

**Comment by jimin9038** [comment]
Failed to connect or create Notion task
(Reason: no assignee)
Please reopen this issue after assigning an assignee

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기](https://www.notion.so/Participant-page-contest-829ed35be7cb4b0388239de467d01693)
