### ISSUE TITLE
[Bug]: docker-compose 의 minio 컨테이너가 stage환경과 local환경에서 혼용되어 생긴 minio console 접근 문제 

### ISSUE THREAD

**Issue by goathoon** [skkuding/codedang#1886]
### Describe the bug

docker-compose 의 minio 컨테이너가 stage환경과 local환경에서 혼용되어 사용되었습니다.
이로 인한 문제로, local환경에서 띄운 minio의 console접근이 stage환경의 minio console로 이동되는 문제가 있습니다.

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기](https://www.notion.so/Participant-page-contest-ffcecb73118249d686cdc3f9395472ae)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기](https://www.notion.so/Participant-page-contest-ffcecb73118249d686cdc3f9395472ae)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기](https://www.notion.so/Participant-page-contest-ffcecb73118249d686cdc3f9395472ae)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Participant page에서 특정 contest에 참가한 모든 참여자들의 성적 및 유저정보 가져오기](https://www.notion.so/Participant-page-contest-ffcecb73118249d686cdc3f9395472ae)

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [[Bug]: docker-compose 의 minio 컨테이너가 stage환경과 local환경에서 혼용되어 생긴 minio console 접근 문제 ](https://www.notion.so/Bug-docker-compose-minio-stage-local-minio-console-62849d84718443988553ba8bf4cb08d2)
