### ISSUE TITLE
admin problem list 페이지 리디자인

### ISSUE THREAD

**Issue by jwoojin9** [skkuding/codedang#1889]
### Describe the problem and solution

admin problem list 페이지 리디자인

### Notion task

TAS-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [admin problem list 페이지 리디자인](https://www.notion.so/admin-problem-list-6dd2d5ff19c044a0b64f1bd66e0f3d14)
