### ISSUE TITLE
메인 페이지 캐러셀 리디자인

### ISSUE THREAD

**Issue by youznn** [skkuding/codedang#1890]
### Describe the problem and solution

메인 페이지 캐러셀에 새로운 디자인을 적용합니다.

### Notion task

TAS-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [메인 페이지 캐러셀 리디자인](https://www.notion.so/1bcb71c92f0040d29a27f90e20277fdd)

**Comment by jimin9038** [comment]
Changed the connected Notion task status to done
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-482 메인 페이지 캐러셀 리디자인](https://www.notion.so/47e95940b80d4db1aeead4d79ada5f62)
