### ISSUE TITLE
Tailwind Config에 Semantic Color 설정 수정

### ISSUE THREAD

**Issue by B0XERCAT** [skkuding/codedang#1892]
### Describe the problem and solution

Tailwind 설정에
Semantic Color primary, level, error를 추가/수정 합니다

### Notion task

TAS-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
**Connected Notion task**
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [Tailwind Config에 Semantic Color 설정 수정](https://www.notion.so/Tailwind-Config-Semantic-Color-e198caa0d00a445986327e2090c52885)
