### ISSUE TITLE
E2E Test 초기 구성

### ISSUE THREAD

**Issue by TAEWOOK-KIMM** [skkuding/codedang#1898]
### Describe the problem and solution

E2E Test 초기 구성중입니다. Playwright 사용해서 POM 객체 방식으로 진행중입니다. 

### Notion task

TAS-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to 진행 중
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-479 E2E Test 초기 구성](https://www.notion.so/E2E-Test-5d859f16785441a295ad2ef6a6653f97)

**Comment by jimin9038** [comment]
Changed the connected Notion task status to 시작 전
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-479 E2E Test 초기 구성](https://www.notion.so/E2E-Test-5d859f16785441a295ad2ef6a6653f97)

**Comment by jimin9038** [comment]
Changed the connected Notion task status to 시작 전
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-479 E2E Test 초기 구성](https://www.notion.so/E2E-Test-5d859f16785441a295ad2ef6a6653f97)

**Comment by jimin9038** [comment]
Changed the connected Notion task status to 시작 전
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-479 E2E Test 초기 구성](https://www.notion.so/E2E-Test-5d859f16785441a295ad2ef6a6653f97)
