### ISSUE TITLE
페이지 배너 리디자인

### ISSUE THREAD

**Issue by youznn** [skkuding/codedang#1902]
### Describe the problem and solution

Problem, Notice, Contest의 배너를 리디자인합니다.

### Notion task

TAS-

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to in-progress
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-484 페이지 배너 리디자인](https://www.notion.so/6e77fca451ce44c89eeea38beb77dffd)

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-483 페이지 배너 리디자인](https://www.notion.so/bd9034c5f16a4c3387686f410a6812b4)
