### ISSUE TITLE
Problem List에서 Accepted 여부 함께 불러오기

### ISSUE THREAD

**Issue by Jaehyeon1020** [skkuding/codedang#1907]
### Describe the problem and solution

![image](https://github.com/user-attachments/assets/82771e52-0fdf-4c85-85aa-7242cd87cb94)
Problem List에서 Accepted 여부를 함께 불러올 수 있도록, getProblems API를 수정합니다.

### Notion task

TAS-598

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-598 Problem List에서 Accepted 여부 함께 불러오기](https://www.notion.so/Problem-List-Accepted-a32d0beaea0d40f2bfff0da783cef274)
