### ISSUE TITLE
Stage서버의 Minio Console 아이디 비밀번호 secret 변수로 주입하기

### ISSUE THREAD

**Issue by beeheavens** [skkuding/codedang#1912]
### Describe the problem and solution

현재 Stage서버의 Minio 접근 계정과 비밀번호가 공개되어 있습니다.
docker-compose.yml파일에서 확인할 수 있습니다.

Github Actions 의 Secrets와 환경 변수를 사용해 docker-compose.yml파일에서 ID와 PW를 확인하지 못하도록 수정합니다.

### Notion task

TAS-415

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-638 Stage서버의 Minio Console 아이디 비밀번호 secret 변수로 주입하기](https://www.notion.so/Stage-Minio-Console-secret-e26b0c415745474ca3e6b647039945ac)
