### ISSUE TITLE
캐러셀 링크 변경

### ISSUE THREAD

**Issue by youznn** [skkuding/codedang#1917]
### Describe the problem and solution

캐러셀 링크를 변경합니다.

### Notion task

TAS-518

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to done
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-644 캐러셀 링크 변경](https://www.notion.so/2b6176d56c5f4fb78fd4e3d3095e8af9)
