### ISSUE TITLE
client contest table column 변경 및 리디자인

### ISSUE THREAD

**Issue by youznn** [skkuding/codedang#1920]
### Describe the problem and solution

cilent contest table
- registered 추가 
- total score 추가
- period column 변경
- search bar 구현
- pagination 구현
<img width="873" alt="image" src="https://github.com/user-attachments/assets/b0b256d3-bb0a-4a47-a97a-539928a1e57a">

### Notion task

TAS-544

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-652 client contest table column 변경 및 리디자인](https://www.notion.so/client-contest-table-column-c327ab73204443daab530bc5c8a48a95)
