### ISSUE TITLE
ESLint custom rule 작성

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#214]
### Describe the problem and solution

Continue from #207 

Parameter 등의 convention을 맞추기 위해 ESLint custom rule을 작성합니다.
custom rule 작성을 위해서는 새로운 패키지를 export해야하므로 별도의 directory에 작성합니다.
여러 rule을 쉽게 관리하기 위해 기존에 `eslintrc.js`에 작성된 rule들도 한 곳에 정의합니다.

#### 작성할 rule

- `route-param-camelcase`: backend의 route param을 camelcase로 통일합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to done
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS- 페이지 배너 리디자인](https://www.notion.so/6e77fca451ce44c89eeea38beb77dffd)
