### ISSUE TITLE
[Feature] Submission 페이지 구현

### ISSUE THREAD

**Issue by jimin9038** [skkuding/codedang#242]
### 🏡 URL for the page

`/problem/[problemId]`

### 🎨 Page Image

![image](https://user-images.githubusercontent.com/73051219/190852187-1d2b7958-c8c1-4f03-9002-00ccb42f734f.png)

### ✏️ Describe the feature

> Note: 디자인은 확정이 아닙니다. 의견 주시면 반영하도록 하겠습니다. 

Problem 모듈의 Submission page를 구현합니다. 
왼쪽 부분에는 한 문제의 Submission list를, 오른쪽 부분에는 Submission detail을 보여줍니다. 

### 🏷 Required APIs

Submission GET API (submission list / submission detail)

### 🏷 Required Components

CodeEditor 
Button
Dropdown
PaginationTable (#129 )

**Comment by goo314** [comment]
아마 url은 problem/[id]/submission으로 되지 않을까 생각합니다.. 🤔

**Comment by jimin9038** [comment]
> 아마 url은 problem/[id]/submission으로 되지 않을까 생각합니다.. 🤔

그게 맞기는 한데 생각해보니까 에디터랑 Submission을 오갈 때 굳이 route가 바뀔 필요가 있을까 싶네요..?? Editor, Standings, Submission 을 각각 컴포넌트로 구성해서 한 페이지로 구성하는 게 어떨까요??

**Comment by goo314** [comment]
anchor로 위치 표시하면 사용자 입장에서 새로고침하기 편하겠군요!
한 페이지로 (페이지 안에 editor, standings, submission 컴포넌트) 진행하는게 좋을 것 같아요 😊

**Comment by jimin9038** [comment]
Changed the connected Notion task status to done
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS- 페이지 배너 리디자인](https://www.notion.so/6e77fca451ce44c89eeea38beb77dffd)
