### ISSUE TITLE
[Feature] admin - group problem pool 페이지 구현

### ISSUE THREAD

**Issue by goo314** [skkuding/codedang#273]
### 🏡 URL for the page

/admin/[groupId]/pool, .../[poolId]

### 🎨 Page Image

Problem Pool List 페이지
![image](https://user-images.githubusercontent.com/62930375/199403997-ad9d8095-72a5-4e68-a474-d252d74e4daa.png)

Problem Pool Detail 페이지
![image](https://user-images.githubusercontent.com/62930375/199404728-bc3bdcb6-9090-4766-9be8-8025f0b49e2b.png)

### ✏️ Describe the feature

해당 그룹의 problem pool list를 관리하는 페이지 입니다.

### 🏷 Required APIs

Problem Pool List 페이지
- 해당 group의 problem pool list를 가져오는 GET api

Problem Pool Detail 페이지
- 해당 pool의 문제, 공유 그룹의 정보를 가져오는 GET api

### 🏷 Required Components

- Pagination Table
- Button
- Modal
- Card Item

**Comment by jimin9038** [comment]
won't implement (기획)
