### ISSUE TITLE
[Feature] admin-problem list 페이지 구현

### ISSUE THREAD

**Issue by hbsongk** [skkuding/codedang#283]
### 🏡 URL for the page

/manager/[groupId]/.../ problem/[problemId]

### 🎨 Page Image

problem list 페이지

![problem pool list](https://user-images.githubusercontent.com/68498323/202348259-8a913ec4-da9a-4bf0-9ed0-437833bfc3fa.png)

### ✏️ Describe the feature

workbook list와 problem pool list에서 문제들을 관리하는 problem list페이지입니다.

### 🏷 Required APIs

Problem List 페이지
- 해당 group의 problem list를 가져오는 GET api

### 🏷 Required Components

- Pagination Table
- Button
- Modal
- SideBar

**Comment by jimin9038** [comment]
won't implement (기획)
