### ISSUE TITLE
Contest Detail 페이지 API 연결

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#319]
### Describe the problem and solution

Contest 상세 페이지에 API를 연결합니다.

![image](https://user-images.githubusercontent.com/19747913/210752210-17ea0cd5-5271-4f30-94b0-a208cbda369e.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
won't implement (기획)
