### ISSUE TITLE
GitHub Projects update 자동화

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#332]
### Describe the problem and solution

GitHub Actions를 이용해 GitHub Project의 task 관련 update를 자동화합니다.

- Issue 등록 시 Project 자동 등록 (+ status, team 자동 설정)
- PR 등록 시 상태 자동 변경 (status 'Review PLZ')
- 리뷰 제출 시 상태 자동 변경 (status 'Under Review' or 'Approved')

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Github projects 사용하지 않음 / Notion task - github issue activepieces로 동기화 구성중.
