### ISSUE TITLE
[Feature] problem 페이지 구현

### ISSUE THREAD

**Issue by st42597** [skkuding/codedang#334]
### 🏡 URL for the page

/problem/id

### 🎨 Page Image

<img width="528" alt="스크린샷 2023-01-10 오후 4 02 51" src="https://user-images.githubusercontent.com/67233988/211483479-9ca6b8f7-b39d-4e82-a9b6-69d77f8b9a8c.png">

### ✏️ Describe the feature

problem 페이지 구현

### 🏷 Required Components
- problem header #249 
- problem navigator #256 
- code editor #313 
- problem clarification #276

**Comment by goo314** [comment]
구현하기 전 알아둬야할 점은... #242 에 언급되어있듯이 Submission과 동일한 페이지입니다!
해당 editor 페이지는 Editor.vue 컴포넌트로 구현해주시고 problem 페이지는 해당 컴포넌트를 import 하는 방식을 사용해주세요 😄 
Editor.vue 컴포넌트가 활성화되었을 경우 url에 anchor 추가해주세요 ~
