### ISSUE TITLE
[Feature] Contest: public contest GET API 구현 

### ISSUE THREAD

**Issue by goo314** [skkuding/codedang#347]
### 1. user가 참여 중인 대회 목록 GET API 구현

기존 프론트엔드 contest list 페이지에서 나타내어야 할 contest 목록은

<img width="400" alt="image" src="https://user-images.githubusercontent.com/62930375/213379651-ea42f3a4-446b-44cd-b7ff-c556e01c57d3.png">

- 현재 user가 참여중인 대회 목록(ongoing)
- 진행되고 있으면서 user가 참여할 수 있는 대회(register-now)
- 시작하지 않은 대회(upcoming)
- 이미 끝난 대회(finished)

였습니다. 하지만 현재 구현된 API는
- 진행중 대회(ongoing)
- 시작하지 않은 대회(upcoming)
- 끝난 대회(finished)

입니다.

둘을 절충할 방안으로 기존 구현된 부분에 추가적으로
- 현재 user가 참여중인 대회 목록

정보를 가져오는 GET API를 구현합니다.

### 2. ContestController의 `getModalContest` method 삭제 및 `getContest` method 추가

현재 contest에서 public contest GET controller가 없는 상황입니다.
`/group/1/contest/:contestId` 로 요청해야 하는데 프론트엔드 쪽에서는 헷갈릴 수 있습니다.

`/contest/:contestId` url로 public contest를 가져오는 코드를 구현합니다.

-> 그와 함께 ContestController의 이름을 PublicContestcontroller로 수정합니다.

### 📚 Describe related database schema

Contest

### 📄 Use-Case(기획)

이하 생략...

**Comment by goo314** [comment]
> ### 2. ContestController의 `getModalContest` method 삭제 및 `getContest` method 추가
> 현재 contest에서 public contest GET controller가 없는 상황입니다. `/group/1/contest/:contestId` 로 요청해야 하는데 프론트엔드 쪽에서는 헷갈릴 수 있습니다.
> 
> `/contest/:contestId` url로 public contest를 가져오는 코드를 구현합니다.
> 
> -> 그와 함께 ContestController의 이름을 PublicContestcontroller로 수정합니다.

추가적인 설명을 하자면, 프론트엔드 쪽 contest 참여 방식이 바뀌면서 getModalContest가 필요없어졌습니다.
기존 : contest를 누르면 modal이 뜨고(getModalContest method 호출) contest 정보 확인 후 참여
현재 : contest를 누르면 바로 detail 페이지로 이동(public contest 정보를 가져오는 api 필요 - 현 groupContestController) 후 참여 버튼을 눌러 참여

**Comment by dotoleeoak** [comment]
> - 현재 user가 참여중인 대회 목록(ongoing)
> - 진행되고 있으면서 user가 참여할 수 있는 대회(register-now)
> - 시작하지 않은 대회(upcoming)
> - 이미 끝난 대회(finished)

ongoing이랑 register-now는 둘 다 진행 중인 대회이고, 가입할 수 있는지만 다르기 때문에,
ongoing items에는 `"is_registered": boolean` field를 추가하는 거 어떨까요?

**Comment by aintbe** [comment]
> Notion
> - ongoing: 진행 중
> - upcoming: 시작 전
> - finished: 끝남

@Hyeongrok1 Upcoming contest도 user가 미리 참여할 수 있도록 기획이 약간 변경되어, 다음과 같이 필드를 구분해주셔야 합니다!
1. ongoing contest 중 이미 user가 참여 중인 대회 목록 (endTime이 작은 순으로 정렬)
2. upcoming contest 중 이미 user가 참여 중인 대회 목록 (startTIme이 작은 순으로 정렬)
3. ongoing contest 중 참여하고 있지 않은 대회 목록 (endTime이 작은 순으로 정렬)
4. upcoming contest 중 user가 참여하고 있지 않은 대회 목록 (startTIme이 작은 순으로 정렬)
5. finished contest (endTime이 작은 순으로 정렬)

최종적으로 `getContests()`가 return하는 객체의 구조는 다음과 같습니다.
```json
{  // 각 번호는 위 리스트에 주어진 번호입니다. 해당 목록을 맞는 번호에 넣으시면 됩니다.
  "registeredOngoing": [1],
  "registeredUpcoming": [2],
  "ongoing": [3],
  "upcoming": [4],
  "finished": [5]
}
```
