### ISSUE TITLE
[Feature] user, group manager, admin 분리

### ISSUE THREAD

**Issue by goo314** [skkuding/codedang#350]
### Describe the problem and solution
변경사항이 많아져서 PR #304 를 닫고 새로 시작합니다.

admin layout을
- leader(group)
- admin

으로 분류합니다.
폴더 구조도 변경할게요!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
won't implement (기획)
