### ISSUE TITLE
JWT `expiresIn` and `exp` does not match

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#381]
### Describe the problem and solution

JWT에 포함된 `expiresIn`의 값이 `exp - iat`의 값과 다릅니다.

#### Access Token

![image](https://user-images.githubusercontent.com/19747913/218957582-00d166d3-67d8-4070-87f2-ea548148d93a.png)

#### Refresh Token

![image](https://user-images.githubusercontent.com/19747913/218957530-722826cb-6593-4885-935e-1ce626fc50e6.png)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
`REFRESH_TOKEN_COOKIE_OPTIONS`에서 설정된 `maxAge` 때문인 것 같습니다! (@aintbe 고마워요)

https://github.com/skkuding/codedang/blob/e4239bef54f8e32ca4d726f82329a6c8ead054bb/backend/src/common/constants.ts#L10-L15

**Comment by jspark2000** [comment]
`access_token`, `refresh_token` 둘 다 차이가 600초 나는데 `JWT 모듈`을 `auth 모듈`에 등록하는 코드에 설정된 '10m'에서 왔을 수 도 있을거 같아요!

https://github.com/skkuding/codedang/blob/e4239bef54f8e32ca4d726f82329a6c8ead054bb/backend/src/auth/auth.module.ts#L14-L25

**Comment by aintbe** [comment]
@jspark2000 네네 아마 `expiresIn`은 maxAge 기준으로 설정이 되고, `exp`는 maxAnge와 signOptions.expireIn 중 더 작은 값으로 설정이 돼서 그런 것 같은데 한번 확인해보겠습니다!

**Comment by jspark2000** [comment]
조심스러운 추측이기는 한데 토큰 생성시에 사용하는 `vertiyAsync` 메소드의 두번째 파라미터 `options?` 에 { expiresIn: number } 를 전달해 보는것은 어떨까요?!

https://github.com/skkuding/codedang/blob/e4239bef54f8e32ca4d726f82329a6c8ead054bb/backend/src/auth/auth.service.ts#L84-L91

```typescript
verifyAsync<T extends object = any>(token: string, options?: JwtVerifyOptions): Promise<T>;

interface JwtSignOptions extends jwt.SignOptions {
    secret?: string | Buffer;
    privateKey?: string | Buffer;
}

export interface SignOptions {
    algorithm?: Algorithm | undefined;
    keyid?: string | undefined;
    /** expressed in seconds or a string describing a time span [zeit/ms](https://github.com/zeit/ms.js).  Eg: 60, "2 days", "10h", "7d" */
    expiresIn?: string | number | undefined;
    /** expressed in seconds or a string describing a time span [zeit/ms](https://github.com/zeit/ms.js).  Eg: 60, "2 days", "10h", "7d" */
    notBefore?: string | number | undefined;
    ...
}


```

**Comment by aintbe** [comment]
@jspark2000 넵 안 그래도 페이로드가 잘못된 것을 확인해서 방금 PR 올렸습니다!ㅎㅎ👍
