### ISSUE TITLE
Public contest get API 문서 작성

### ISSUE THREAD

**Issue by Hyeongrok1** [skkuding/codedang#415]
### Describe the problem and solution

Public contest get API에 관한 문서를 작성합니다.
#371 를 참고해주세요

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
@Hyeongrok1 혹시 이슈 왜 닫힌 건가요??

**Comment by Hyeongrok1** [comment]
@dotoleeoak 문서 작성 전에 API를 수정할 일이 있는 것 같아서 이슈를 닫았었습니다! 그런데 생각해보니 이슈를 닫을 이유는 없었네요..

**Comment by dotoleeoak** [comment]
@Hyeongrok1 넵 ㅎㅎ 알겠습니다
