### ISSUE TITLE
Group 목록을 로그인하지 않은 유저가 열람할 수 없음

### ISSUE THREAD

**Issue by aintbe** [skkuding/codedang#417]
### Describe the problem and solution

Group 목록을 로그인하지 않은 유저가 열람하는 것이 불가능합니다. 해당 엔드포인트에 `@AuthNotNeeded()` 데코레이터를 붙여 해결합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
Resolved in #418
