### ISSUE TITLE
No Efficient Way to Get Cursor of the Last Page

### ISSUE THREAD

**Issue by aintbe** [skkuding/codedang#432]
### Describe the problem and solution

현재 프론트엔드의 페이지네이션 컴포넌트는 항상 첫번째 페이지, 전 페이지, 현재 페이지, 뒷 페이지, 마지막 페이지 전부에 접근 가능한 상황을 전제로 디자인되어 있습니다.

- 프론트엔드에서 컴포넌트 수정 → 디자인 tradeoff
- 백엔드에서 마지막 커서를 항상 읽어오도록 수정 → 성능 tradeoff

두 경우 모두 문제의 소지가 있어 논의 중입니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
⚠️ case study가 필요합니다

**Comment by aintbe** [comment]
백엔드에서 성능 저하를 감수하기보다 컴포넌트를 수정하는 것으로 결정했습니다. 대신 cursor-based pagination의 장점을 살릴 수 있도록, 프론트엔드에서 여러 페이지에 걸쳐 보여줄 아이템 목록 전체를 한 번에 요청하고, 화살표로 생략되어 보이지 않는 페이지로 넘어갈 때만 새로 요청을 하는 방향으로 구현합니다.
