### ISSUE TITLE
[Feature] Implement Search APIs

### ISSUE THREAD

**Issue by aintbe** [skkuding/codedang#433]
### 📌 Describe the feature

검색창에서 활용될 검색 API를 구현합니다.

### 📚 Describe related database schema

TBD

### 📄 Use-Case(기획)

- 레코드 내용에서 입력된 키워드를 찾아 매칭되는 레코드를 반환합니다.

**Comment by dotoleeoak** [comment]
#1122 에서 구현하였습니다
