### ISSUE TITLE
[Bug]: problem page code-mirror non-fixed size

### ISSUE THREAD

**Issue by st42597** [skkuding/codedang#448]
### Describe the bug

<img width="1728" alt="스크린샷 2023-03-23 오후 2 36 33" src="https://user-images.githubusercontent.com/67233988/227113486-49761042-a56d-43c8-9c6f-a9609428aa17.png">
code editor에서 긴 문장을 작성했을 때 code editor 영역이 확장돼서 다른 영역을 강제로 좁히는 문제

### Reproduction

1. code editor 영역에 긴 문장을 작성한다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to done
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS- 페이지 배너 리디자인](https://www.notion.so/6e77fca451ce44c89eeea38beb77dffd)
