### ISSUE TITLE
Group Notice API 문서 update

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#451]
### Describe the problem and solution

Cursor-based pagination이 thunder client 문서에 반영이 안되어있어요...!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by aintbe** [comment]
이거 #455 에 올라가 있을 거예요...!!
