### ISSUE TITLE
[Chore] apply NestJS vscode material icon 

### ISSUE THREAD

**Issue by jspark2000** [skkuding/codedang#475]
### Description
vscode devcontainer 사용시에 NestJS 관련 파일들이 Angular 아이콘이 아닌 NestJS 아이콘으로 표시될 수 있도록 vscode 설정을 수정합니다.

### Reference
https://github.com/PKief/vscode-material-icon-theme/issues/503

### Others
`./.vscode/settings.json` 파일에 아래처럼 코드를 추가합니다.
```json
{
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.formatOnSave": true,
  "thunder-client.saveToWorkspace": true,
  "[prisma]": {
    "editor.defaultFormatter": "Prisma.prisma"
  },
  // 아래의 코드 추가
  "material-icon-theme.activeIconPack": "nest"
}
```

### Before
<img width="194" alt="image" src="https://github.com/skkuding/codedang/assets/102132161/b379898e-5ed8-4f6f-a291-a85c864c5a23">

### After
<img width="191" alt="image" src="https://github.com/skkuding/codedang/assets/102132161/c47caf16-ce11-44f4-91a9-2da894ec20d2">

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
이거 전에 해보려고 했는데 material icon 설정이 user setting만 적용되고 workspace setting은 적용이 안됐는데,
지금은 workspace setting도 잘 적용되나요?
