### ISSUE TITLE
group notice detail page

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#636]
### Describe the problem and solution

group notice의 detail page를 만든다
api도 있어서 같이 연결해주세요~

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
기획 변동으로 아직 구현하지 않음 (추후 구현할 때 다시 올릴게요)
