### ISSUE TITLE
group contest detail page

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#646]
### Describe the problem and solution

group contest 의 detail page를 만든다
api도 있어서 같이 연결해주세요~

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by EliseCho13** [comment]
현재 contest/[id]로 되어 있는 url을 group/[id]/contest/[id]으로 바꿔야 하는 것. 우선순위가 낮아 미뤄짐.

**Comment by jimin9038** [comment]
기획 변동으로 아직 구현하지 않음 (추후 구현할 때 다시 올릴게요)
