### ISSUE TITLE
Volar Takeover mode를 기본으로 설정

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#665]
### Describe the problem and solution

VSCode의 Vue language extension인 Volar의 Takeover mode를 기본으로 활성화합니다.
공식 문서: https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode

Takeover mode를 사용하면 Typescript용 language server를 하나만 실행해 효율적입니다.

> **Warning**
> 처음 환경 세팅 시 builtin typescript extension을 직접 disable해야합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
스택 변동으로 구현하지 않음
