### ISSUE TITLE
vite-plugin-pages 대체

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#682]
### Describe the problem and solution

> We recommend Vue user using [unplugin-vue-router](https://github.com/posva/unplugin-vue-router) instead of this plugin.

[vite-plugin-pages 공식 가이드](https://github.com/hannoeru/vite-plugin-pages#getting-started)에 따라 unplugin-vue-router로 plugin을 대체합니다.
https://github.com/posva/unplugin-vue-router

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
스택 변경으로 구현하지 않음
