### ISSUE TITLE
Force Admin & SuperAdmin to be GroupLeaders When Joining Groups

### ISSUE THREAD

**Issue by aintbe** [skkuding/codedang#748]
### Describe the problem and solution

Admin 혹은 SuperAdmin이 그룹에 가입할 시 자동으로 GroupLeader로 설정되며, 역할은 변경될 수 없습니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by cho-to** [comment]
참고로 역할이 변경(`downgrade`)될 수 없는 부분은 #596 admin group member api  에서 구현하면 될 것 같습니다!
