### ISSUE TITLE
로그인 및 회원가입 페이지로 만들기

### ISSUE THREAD

**Issue by dayongkr** [skkuding/codedang#786]
### Describe the problem and solution

![image](https://github.com/skkuding/codedang/assets/50468628/6c5fac47-f03d-454c-9436-ab433ca759e2)

위와 같은 디자인으로 수정

회의 결과 우선순위는 낮아서 추후에 진행할 예정

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
현재 상태 유지
