### ISSUE TITLE
Terragrunt로 terraform 모듈화

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#810]
### Describe the problem and solution

Terraform의 lightweight wrapper인 Terragrunt로 모듈, 폴더, 파일 등을 보다 효율적으로 관리합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
테라폼 리팩토링 완료 @goathoon 혹시 남겨두는 게 좋나요?

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-495 Terragrunt로 terraform 모듈화](https://www.notion.so/Terragrunt-terraform-99312b5ca9c040f5bc52ac4dc6c71a28)

**Comment by goathoon** [comment]
일단 중단할까요..? ㅎㅎ.. Terrafrunt까지 도입하긴 좀 무리가있지않나 싶습니다. 지금 당장은..?
