### ISSUE TITLE
[Bug]: 회원가입 Email 전송 실패

### ISSUE THREAD

**Issue by k1g99** [skkuding/codedang#848]
### Describe the bug

ECS 권한 문제로 가입 시 Authentication code Email 전송이 실패합니다. 

### Reproduction

1.
2.
3.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
#844 코드 배포 아직 안되지 않았나?

**Comment by k1g99** [comment]
아하 이거 에러 로그가 Instance에 권한이 없다고 하길래 필요할 줄 알았는데 아니네 
코드 작성한대로 Taks Roleㅇ만 붙어있음 될듯!!!
