### ISSUE TITLE
Vue → React migration

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#853]
### Describe the problem and solution

Frontend 라이브러리를 Vue에서 React로 migrate합니다.
이에 따른 비용이 상당할 것으로 예상하지만, 디자인 리뉴얼이 예정되어있어 함께 적용하면 좋을 것 같습니다.

#### React로 바꾸는 이유

- 경험 많은 팀원을 구하기 쉽다.
- 풍부한 생태계
- 자료, 사례를 찾기 쉽다.

#### Checklist

- [ ] Next.js 적용
- [ ] UI library 적용

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
완료된 이슈
