### ISSUE TITLE
[Bug]: Client Cluster Segmentation Fault

### ISSUE THREAD

**Issue by k1g99** [skkuding/codedang#855]
### Describe the bug

Client ECS Cluster의 Task가 Request를 감당하지 못하고 죽는 경우가 발생합니다. 

![image](https://github.com/skkuding/codedang/assets/100272259/08ed601e-5ffa-445b-85fd-5414f74143bc)

![image](https://github.com/skkuding/codedang/assets/100272259/9b4047c7-ac41-4c89-bf24-e6700581c194)

 **--- UPDATE ---**
Problem 페이지에 접속하는 경우 Segmentation Fault가 발생합니다.
![image](https://github.com/skkuding/codedang/assets/100272259/2fe7d1f6-5fdb-4ff2-907c-27c8495556fc)

### Reproduction

1. Codedang 페이지 접속 시 발생 (Problem 페이지)
2.
3.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
#867 에서 해결되었습니다!
