### ISSUE TITLE
Frontend asset 압축 (gzip/brotli)

### ISSUE THREAD

**Issue by dotoleeoak** [skkuding/codedang#919]
### Describe the problem and solution

페이지 로드 성능 향상을 위해, gzip 또는 brotli 압축을 적용합니다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
스택 변경으로 구현하지 않음
