### ISSUE TITLE
admin의 deleteProblem api 연결

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#922]
### Describe the problem and solution

admin이 문제를 삭제할 수 있게 api를 연결 해보자

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
구현되어 있음
