### ISSUE TITLE
[Bug]: useListGraphQL 에서 option이 없을 때 안쓰고 싶다

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#929]
### Describe the bug

useListGraphQL 사용 시 기본 option을 사용하고 싶을 때 
지금은 option이 필수여서 빈 객체를 넣어줘야 되는데 좀 불편할 것 같아요!

### Reproduction

1.
2.
3.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
#930에서 구현
