### ISSUE TITLE
group admin의 problem edit 페이지

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#935]
### Describe the problem and solution

group admin의 problem edit 페이지 만들기
table을 클릭하면 create 할 때 있던 페이지에 문제 정보들이 채워져서 나오게 한다
create 페이지를 component화 한다

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
기획 변동으로 구현하지 않음
