### ISSUE TITLE
네이버 서치어드바이저 - 사이트 소유확인

### ISSUE THREAD

**Issue by dayongkr** [skkuding/codedang#940]
### Describe the problem and solution

사이트 소유 확인을 위해 index.html 파일에 meta태그 추가
> SEO 작업!

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
Changed the connected Notion task status to not-started
## <img src="https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png?20200221181224" width="20" height="20"> [TAS-501 네이버 서치어드바이저 - 사이트 소유확인](https://www.notion.so/7653322abb1c4d88b20e796d28dcf77c)
