### ISSUE TITLE
[Bug]: 문제 전환 시 이전 코드가 남는다

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#957]
### Describe the bug

문제를 풀다가 다른 문제로 전환 할 경우 이전에 작성했던 코드가 다른 문제 코드 작성란에도 똑같이 보인다

### Reproduction

1. local storage에 각 문제별 풀이코드를 저장한다
2. 새로운 문제로 전환할 시 기존 코드창은 깨끗하게 비워져야 한다.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
구현 완료됨 https://github.com/skkuding/codedang/pull/1720
