### ISSUE TITLE
[Bug]: user 로 로그인 시 management/settings 안보이게하기

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#958]
### Describe the bug

![image](https://github.com/skkuding/codedang/assets/72334086/bfb08312-3f82-43cd-ba3a-be2280ad3fd1)

### Reproduction

1.
2.
3.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by EliseCho13** [comment]
management는 추후 admin 페이지로 연결되는 건가요?
setting은 유저 개별 세팅이라고 생각했는데 아니라면 어떤 기능인가요?

**Comment by jimin9038** [comment]
구현되어 있음
