### ISSUE TITLE
홈 화면 네비게이션 바 순서 변경

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#976]
### Describe the problem and solution

notice problem group contest로 변경하기

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by EliseCho13** [comment]
이거 지금 hotfix로 올려도 되나요? email value 수정하는 게 너무 빨리 끝나서...

**Comment by dotoleeoak** [comment]
> 이거 지금 hotfix로 올려도 되나요? email value 수정하는 게 너무 빨리 끝나서...

좋아유

**Comment by dotoleeoak** [comment]
@EliseCho13 혹시 이것도 수정 가능할까요?
네비게이션 바 순서만 바꾸면 돼요
https://www.notion.so/bf3c80c4bd5e4763b46056d54cd31cce?pvs=4

notice - contest - problem - group
→ notice - **problem** - contest - group
