### ISSUE TITLE
[Bug]: 문제 풀다 페이지 이동 시 코드 저장

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#977]
### Describe the bug

그리고 코드 초기화

### Reproduction

1.  
2.
3.
   

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by EliseCho13** [comment]
이슈 #957 과 중복
