### ISSUE TITLE
[Bug]: 문제 생성 시 태그 선택란

### ISSUE THREAD

**Issue by Kohminchae** [skkuding/codedang#979]
### Describe the bug

만들기 

### Reproduction

1.
2.
3.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by jimin9038** [comment]
기획 변동으로 TAG 기능 삭제
