### ISSUE TITLE
Next.JS authentication 방식 선정

### ISSUE THREAD

**Issue by dayongkr** [skkuding/codedang#983]
### Describe the problem and solution

- Next Auth 라이브러리를 사용한다.
  - Next Auth는 Next.JS의 API Routes를 사용해서 별도의 API로 유저의 요청을 받기 때문에 Next.JS에서 한 번 더 nest 서버로 로그인이 가능한지 요청을 보내야 함 -> 즉 http 요청 2 번 발생
  - Next Auth의 token안에 nest 서버의 assess 토큰을 넣어 구현하게 되면 인증이 필요한 API 요청을 보낼 때마다 Next Auth의 token을 decode하고 안에서 access token을 꺼내어야 함
  - CSRF 토큰을 추가로 유지해서 토큰들을 모두 쿠키에 저장하기 때문에 `getServerSession` 함수를 통해 rsc에서도 유저 정보 및 로그인 여부를 확인 할 수 있어 추가적인 상태 관리 라이브러리가 필요 없게 된다.
- Next Auth 라이브러리를 사용 안한다.
  - vue처럼 fetch로 로그인 요청 후 refresh token은 쿠키에 저장
  - access token은 쿠키에 저장하면 CSRF 공격에 취약하다고 함 따라서 전역 변수인 zustand에 저장하고 필요할 때만 header 집어 넣어 인증 => 최상위 컴포넌트을 rcc로 만들고 provider로 감싸야 하기 때문에 사실상 rsc는 못씀
 
상태관리 라이브러리를 사용하지 않으면서 access token을 안전하게 보관하고 유저 정보를 저장하는 방법을 잘 고려한다면 Next Auth 라이브러리 사용 안하는 방향이 좋아보임

### Validations

- [X] Follow our [Code of Conduct](https://github.com/skkuding/next/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/skkuding/next/blob/main/CONTRIBUTING.md)
- [X] Check that there isn't already an issue

**Comment by dotoleeoak** [comment]
> access token은 쿠키에 저장하면 CSRF 공격에 취약하다고 함 따라서 전역 변수인 zustand에 저장하고 필요할 때만 header 집어 넣어 인증 => 최상위 컴포넌트을 rcc로 만들고 provider로 감싸야 하기 때문에 사실상 rsc는 못씀

Next Auth를 쓰든 안 쓰든 일단 client side에서 auth 토큰을 포함해서 API 호출할 일은 있을 거 같은데, auth 토큰을 최상위 컴포넌트에 담아야 한다면 Next Auth 사용 여부에 관계 없이 항상 server component를 못 쓰는 거 아닌가요?
